
  - include: debian.yml
    when: ansible_os_family == "Debian"

  - name: Link .bashrc
    file:
      src: "bashrc"
      dest: "{{ user_home }}/.bashrc"
      state: link

  - name: Link .bash_aliases
    file:
      src: "bash_aliases"
      dest: "{{ user_home }}/.bash_aliases"
      state: link

  - name: Link .inputrc
    file:
      src: "inputrc"
      dest: "{{ user_home }}/.inputrc"
      state: link

  - name: Check if base16 exists
    stat: path="{{ user_home }}/.config/base16-shell"
    register: base16_dir

  - name: Add base16
    git:
      repo=https://github.com/chriskempson/base16-shell.git 
      dest="{{ user_home }}/.config/base16-shell"
      accept_hostkey=yes
    when: not base16_dir.stat.exists

 - name: Link Xresources
   file:
     src: templates/Xresources
     dest: "{{ user_home }}/Xresources"
     state: link

