
  - include: debian.yml
    when: ansible_os_family == "Debian"

  - include: arch.yml
    when: ansible_os_family == "Archlinux"

  - name: Stat .bashrc
    stat: path="{{ user_home }}/.bashrc"
    register: stat_bashrc

  - name: Stat .bash_aliases
    stat: path="{{ user_home }}/.bash_aliases"
    register: stat_bash_aliases

  - name: Stat .inputrc
    stat: path="{{ user_home }}/.inputrc"
    register: stat_inputrc

  - name: Backup .bashrc
    command: mv  "{{ user_home }}/.bashrc" "{{ user_home }}/.bashrc.bak"
    when: stat_bashrc.stat.exists

  - name: Backup .bash_aliases
    command: mv "{{ user_home }}/.bash_aliases" "{{ user_home }}/.bash_aliases.bak"
    when: stat_bash_aliases.stat.exists

  - name: Backup .inputrc
    command: mv "{{ user_home }}/.inputrc" "{{ user_home }}/.inputrc.bak"
    when: stat_inputrc.stat.exists

  - name: Link .bashrc
    file:
      src:  "{{ dotfiles_dir }}/ansible/roles/rxvt/files/bashrc"
      dest: "{{ user_home }}/.bashrc"
      state: link

  - name: Link .bash_aliases
    file:
      src:  "{{ dotfiles_dir }}/ansible/roles/rxvt/files/bash_aliases"
      dest: "{{ user_home }}/.bash_aliases"
      state: link

  - name: Link .inputrc
    file:
      src:  "{{ dotfiles_dir }}/ansible/roles/rxvt/files/inputrc"
      dest: "{{ user_home }}/.inputrc"
      state: link

  - name: Check if base16 exists
    stat: path="{{ user_home }}/.config/base16-shell"
    register: base16_dir

  - name: Add base16
    git:
      repo=https://github.com/chriskempson/base16-shell.git 
      dest="{{ user_home }}/.config/base16-shell"
      accept_hostkey=yes
    when: not base16_dir.stat.exists

  - name: Link Xresources
    file:
      src:  "{{ dotfiles_dir }}//ansible/roles/rxvt/files/Xresources"
      dest: "{{ user_home }}/.Xresources"
      state: link
    register: xresources

  - name: run xrdb
    command: xrdb -merge "{{ user_home }}/.Xresources"
    when: xresources.changed and not lookup('env', 'CI') and not lookup('env', 'Vagrant')
    ignore_errors: true



