
  - name: Install dependencies
    pacman:
      name: "{{ item }}"
      state: latest
    with_items:
      - base-devel
      - yajl
      - package-query

  - name: Check if yaourt is installed
    stat:
      path: "{{ user_home }}/source/yaourt"
    failed_when: false
    changed_when: false
    register: yaourt_installed

  - name: Pull yaourt source
    git:
      repo: https://aur.archlinux.org/yaourt.git
      dest: "{{ user_home }}/source/yaourt"
    register: yaourt_git
    when: not yaourt_installed.stat.exists

  - name: Set source dir permissions
    file:
      path: "{{ user_home }}/source/yaourt"
      owner: "{{ username }}"
      recurse: yes
    when: yaourt_git.changed

  - name: Run makepkg
    command: "makepkg -si"
    args:
      chdir: "{{ user_home }}/source/yaourt"
    become_user: "{{ username }}"
    when: yaourt_git.changed

