#!/usr/bin/fish

set default_root "$HOME/dotfiles/tfconfig/src/tfconfig/modules/utils/files/local_scripts"
set -q local_scripts_root || set local_scripts_root $default_root
set dir $local_scripts_root

echo $local_scripts_root

set index 1

while test $index -lt (count $argv);
  set dir $dir/$argv[$index]
  mkdir -p $dir
  set index (math $index + 1)
end

set cmd $argv[$index]
set file $dir/$cmd

echo "#!/usr/bin/fish" > $file
echo "" >> $file
$VISUAL $file
chmod +x $file

# Update completions
fish $XDG_CONFIG_HOME/fish/completions/s.fish
