
 - name: Read /proc/cpuinfo
   command: cat /proc/cpuinfo
   register: cpuinfo

 - name: Check for CI
   set_fact:
     ci: "{{ lookup('env', 'CI') or lookup('env', 'ci') }}"
     debian: "{{ ansible_os_family == 'Debian' }}"
     arch: "{{ ansible_os_family == 'Archlinux' }}"
     is_vm: cpuinfo | search('hypervisor')
   tags:
     - always

