image: base/archlinux

before_script:
  - ls -l
  - whoami
  - env
  - uptime
  - cat /etc/os-release
  - df -h
    #  - sed -i -e 's/\/home\/johan\/dotfiles/$TRAVIS_BUILD_DIR/g' ansible/group_vars/local.yml
  - sed -i -e 's/johan/johan1a/g' ansible/group_vars/local.yml
  - cat /etc/os-release
  - pacman -Syu
  - pacman -S sudo --noconfirm
  - useradd johan1a
  - usermod -aG wheel johan1a
  - echo "johan1a   ALL=(ALL) ALL" >> /etc/sudoers
  - echo "Defaults:johan1a      !authenticate" >> /etc/sudoers
  - chown johan1a -R home/johan1a/.ansible
  - cat /etc/sudoers

test:
  script:
    - sudo -u johan1a whoami
    - sudo -u johan1a ./bootstrap.sh

