image: base/archlinux

before_script:
  - ls -l
  - whoami
  - env
  - uptime
  - cat /etc/os-release
  - df -h
    #  - sed -i -e 's/\/home\/johan\/dotfiles/$TRAVIS_BUILD_DIR/g' ansible/group_vars/local.yml
  - sed -i -e 's/johan/gitlab/g' ansible/group_vars/local.yml
  - cat /etc/os-release
  - pacman -Syu
  - pacman -S sudo --noconfirm
  - useradd gitlab
  - usermod -aG wheel gitlab
  - cat /etc/sudoers

test:
  script:
    - sudo -u gitlab whoami
    - sudo -u gitlab ./bootstrap.sh

