image: base/archlinux

before_script:
  - ls -l
  - whoami
  - env
  - uptime
  - cat /etc/os-release
  - df -h
  - sed -i -e 's/johan/johan1a/g' ansible/group_vars/local.yml
  - cat /etc/os-release
  - pacman -Syu
  - pacman -S sudo git --noconfirm
  - useradd johan1a
  - usermod -aG wheel johan1a
  - echo "johan1a   ALL=(ALL) ALL" >> /etc/sudoers
  - echo "Defaults:johan1a      !authenticate" >> /etc/sudoers
  - mkdir /home/johan1a
  - chown johan1a /home/johan1a -R

test:
  script:
    - sudo -E -u johan1a env
    - CI=True sudo -u johan1a ./bootstrap.sh

