image: archlinux

before_script:
  - ls -l
  - whoami
  - env
  - uptime
  - cat /etc/os-release
  - df -h
    #  - sed -i -e 's/\/home\/johan\/dotfiles/$TRAVIS_BUILD_DIR/g' ansible/group_vars/local.yml
  - sed -i -e 's/johan/travis/g' ansible/group_vars/local.yml
  # - apt-get -qq update
  # - apt-cache madison libtool-bin
  # - apt search libtool-bin
  # - apt search libtool
  - cat /etc/os-release

test:
  script:
    - whoami
    - sh bootstrap.sh

