image: archlinux/base

before_script:
  - ls -l
  - whoami
  - env
  - uptime
  - cat /etc/os-release
  - df -h
  - cat /etc/os-release
  - sed -i -e 's/johan/johan1a/g' ansible/group_vars/local.yml
  - sed -i -e 's/home\/johan1a\/dotfiles/builds\/johan1a\/dotfiles/g' ansible/group_vars/local.yml
  - pacman -Syu --noconfirm
  - pacman -S sudo git --noconfirm
  - useradd johan1a
  - usermod -aG wheel johan1a
  - echo "johan1a   ALL=(ALL) ALL" >> /etc/sudoers
  - echo "Defaults:johan1a      !authenticate" >> /etc/sudoers
  - mkdir /home/johan1a
  - chown johan1a /home/johan1a -R

test:
  script:
    - sudo -u johan1a bash -c 'export CI=True; ./bootstrap.sh hunter2'

