profiles:
  - name: work
    pattern: ".*307.*"
    has-monitor: true
    ignored-modules:
      - owncloud
      - mail
  - name: server
    pattern: ".*urdatorn.*"
    has-monitor: false
    ignored-modules:
      - owncloud
      - mail
  - name: ci
    pattern: "runner-.*"
    has-monitor: false
    ignored-modules:
      - owncloud
  - name: default
    pattern: ".*"
    has-monitor: true
    ignored-modules:
      -
modules:
  - dirs
  - packages
  - docker
  - cups
  - mlocate
  - git
  - ctags
  - intellij
  - owncloud
  - taskwarrior
  - i3_gaps
  - aur
  - mail
  - neovim
  - xorg
  - terminal
  - fzf
  - tmux
  - colemak
  - dunst
  - polybar
  - gpg
