profiles:
  - name: work
    pattern: ".*307.*"
    has-monitor: true
    ignored-modules:
      - owncloud
      - pulseaudio
      - pipewire
      - forensic_tools
  - name: server
    pattern: ".*urdatorn.*"
    has-monitor: false
    ignored-modules:
      - owncloud
      - polybar
      - gnome_keyring
      - pipewire
  - name: rpi
    os: raspbian
    pattern: "tiltpi"
    has-monitor: false
    additional-modules:
      - packages_apt
    ignored-modules:
      - packages
      - pulseaudio
      - pipewire
      - docker
      - cups
      - mlocate
      - intellij
      - owncloud
      - taskwarrior
      - i3_gaps
      - aur
      - xorg
      - colemak
      - dunst
      - polybar
      - gpg
      - gnome_keyring
  - name: ci
    pattern: "ci|runner-.*"
    has-monitor: false
    ignored-modules:
      - owncloud
      - pulseaudio
      - pipewire
      - cups
  - name: default
    pattern: ".*"
    has-monitor: true
modules:
  - dirs
  - git_hooks
  - packages
  - utils
  - docker
  - cups
  - mlocate
  - git
  - ctags
  - intellij
  - owncloud
  - taskwarrior
  - i3_gaps
  - aur
  - neovim
  - xorg
  - terminal
  - tmux
  - colemak
  - pipewire
  - dunst
  - polybar
  - gpg
  - forensic_tools
