profiles:
  - name: work
    pattern: ".*307.*"
    has-monitor: true
    ignored-modules:
      - owncloud
      - pulseaudio
    additional-modules:
      - pipewire
  - name: server
    pattern: ".*urdatorn.*"
    has-monitor: false
    ignored-modules:
      - owncloud
      - polybar
      - gnome_keyring
  - name: rpi
    os: raspbian
    pattern: "tiltpi"
    has-monitor: false
    additional-modules:
      - packages_apt
    ignored-modules:
      # - dirs
      - packages
      - pulseaudio
      # - utils
      - docker
      - cups
      - mlocate
      # - git
      # - ctags
      - intellij
      - owncloud
      - taskwarrior
      - i3_gaps
      - aur
      # - neovim
      - xorg
      # - terminal
      # - tmux
      - colemak
      - dunst
      - polybar
      - gpg
      - gnome_keyring
  - name: ci
    pattern: "runner-.*"
    has-monitor: false
    ignored-modules:
      - owncloud
      - pulseaudio
    additional-modules:
      - pipewire
  - name: default
    pattern: ".*"
    has-monitor: true
modules:
  - dirs
  - git_hooks
  - packages
  - pulseaudio
  - utils
  - docker
  - cups
  - mlocate
  - git
  - ctags
  - intellij
  - owncloud
  - taskwarrior
  - i3_gaps
  - aur
  - neovim
  - xorg
  - terminal
  - tmux
  - colemak
  - dunst
  - polybar
  - gpg
  - gnome_keyring
