
  - name: Install herbstluftwm
    apt: name=herbstluftwm
         state=latest
    become_method: sudo

  - name: create config dir
    file:
      path: "{{ user_home }}/.config/herbstluftwm"
      state: directory

  - name: remove old herbstluftwm config
    file:
      path: "{{ user_home }}/.config/herbstluftwm/autostart"
      state: absent
    become: true

  - name: Link herbstluftwm config
    file:
      src: "{{ user_home }}/dotfiles/ansible/roles/herbstluftwm/templates/autostart"
      dest: "{{ user_home }}/.config/herbstluftwm/autostart"
      state: link
      owner: "{{ username }}"

