
  - name: Install xorg
    pacman:
      name: ['xorg', 'xorg-xinit', 'xorg-server']
      state: latest
    when: username != "vagrant"

  - name: Link .xinitrc config
    script: >
          scripts/install_dotfile
          "{{ dotfiles_dir }}/ansible/roles/xinitrc/templates/xinitrc_arch"
          "{{ user_home }}/.xinitrc"
