
  - name: Install xorg
    pacman:
      name: "{{ item }}"
      state: latest
    when: username != "vagrant"
    with_items:
      - xorg
      - xorg-xinit
      - xorg-server

  - name: Link .xinitrc config
    script: >
          scripts/install_dotfile
          "{{ dotfiles_dir }}/ansible/roles/xinitrc/templates/xinitrc_arch"
          "{{ user_home }}/.xinitrc"
