
  - name: Install xorg
    pacman:
      name: "{{ item }}"
      state: latest
    when: username != "vagrant"
    with_items:
      - xorg
      - xorg-xinit
      - xorg-server

  - command: test -L "{{ user_home }}/.xinitrc"
    register: isLink
    changed_when: false
    failed_when: false

  - command: test -f "{{ user_home }}/.xinitrc"
    register: isFile
    changed_when: false
    failed_when: false

  - name: Backup .xinitrc
    command: mv "{{ user_home }}/.xinitrc" "{{ user_home }}/.dotfiles_backup/.xinitrc"
    when: isFile.rc == 0

  - name: Link .xinitrc config
    file:
      src: "{{ dotfiles_dir }}/ansible/roles/xinitrc/templates/xinitrc_arch"
      dest: "{{ user_home }}/.xinitrc"
      state: link
    changed_when: not (isFile.rc == 0 and isLink.rc == 0)

