
  - name: Create ~/.xmonad
    file:
      path: "{{ user_home }}/.xmonad/"
      state: directory

  - name: Remove xmonad.hs
    file:
      path: "{{ user_home }}/.xmonad/xmonad.hs"
      state: absent

  - name: Link xmonad.hs
    file:
      src: "{{ dotfiles_dir }}/ansible/roles/xmonad/templates/xmonad.hs"
      dest: "{{ user_home }}/.xmonad/xmonad.hs"
      state: link
