
  - name: Install software-properties-common
    apt: name=software-properties-common
    become_method: sudo

  - name: Add apt repository ppa:neovim-ppa/stable
    become: true
    apt_repository:
      repo: ppa:neovim-ppa/stable
      state: present
    register: neovim_repo

  - name: Update apt
    become: true
    apt:
      update_cache: yes
    when: neovim_repo.changed

  - name: install neovim
    apt: name=neovim state=latest
    become_method: sudo

  - name: Install neovim pip3 package
    pip:
      name: neovim
      state: latest
      executable: pip

