
  - include: debian.yml
    when: ansible_os_family == "Debian"

  - name: Remove default neovim config
    file:
      path: "{{ user_home }}/{{ item }}"
      state: absent
    with_items:
      - .config/nvim
      - .vim/init.vim

  - name: Link neovim to vim config
    file:
      dest: "{{ user_home }}/.config/nvim" 
      src: "{{ user_home }}/.vim"
      state: link

  - name: Copy .vimrc
    template:
      src: "vimrc"
      dest: "{{ user_home }}/.vimrc"

  - name: Link init.vim to .vimrc
    file:
      src: "{{ user_home }}/.vimrc"
      dest: "{{ user_home }}/.config/nvim" 
      state: link

  - name: Install Vundle
    git: repo=https://github.com/VundleVim/Vundle.vim.git
         dest="{{ user_home }}/.vim/bundle/Vundle.vim"
         accept_hostkey=yes
