
  - include: debian.yml
    when: not ci and ansible_os_family == "Debian"
    tags: neovim

  - include: arch.yml
    when: not ci and ansible_os_family == "Archlinux"
    tags: neovim

  - include: neovim.yml
    when: not ci
    tags: neovim
