
  - name: Install neovim gem
    gem:
      name: neovim
      state: latest

  - name: Install neovim pip package
    pip:
      name: neovim
      state: latest

  - name: Install neovim pip3 package
    pip:
      name: neovim
      state: latest
      executable: pip3

  - name: Stat vimrc 
    stat: path="{{ user_home }}/.vimrc"
    register: vimrc_stat

  - name: Stat .config/nvim 
    stat: path="{{ user_home }}/.config/nvim"
    register: nvim_stat

  - name: Stat .vim/init.vim 
    stat: path="{{ user_home }}/.vim/init.vim"
    register: init_vim_stat

  - name: Remove .config/nvim if it's a symlink
    file:
      path: "{{ user_home }}/.config/nvim"
      state: absent
    when: nvim_stat.stat.islnk is defined and nvim_stat.stat.islnk

  - name: Remove .vim/init.vim if it's a symlink
    file:
      path: "{{ user_home }}/.vim/init.vim"
      state: absent
    when: init_vim_stat.stat.islnk is defined and init_vim_stat.stat.islnk

  - name: Make sure .vim exists
    file:
      path: "{{ user_home }}/.vim"
      state: directory

  - name: Link neovim to vim config
    file:
      src: "{{ user_home }}/.vim"
      dest: "{{ user_home }}/.config/nvim" 
      state: link

  - name: Backup vimrc
    command: mv "{{ user_home }}/.vimrc" "{{ user_home }}/.vimrc.bak"
    when: vimrc_stat.stat.exists

  - name: Symlink .vimrc
    file:
      src: "{{ dotfiles_dir }}/ansible/roles/neovim/templates/vimrc"
      dest: "{{ user_home }}/{{ item }}"
      state: link
    with_items:
      - .vimrc
      - .vim/init.vim

  - name: Check if Vundle exists
    stat: path="{{ user_home }}/.vim/bundle/Vundle.vim"
    register: vundle_dir

  - name: Install Vundle 
    git: repo=https://github.com/VundleVim/Vundle.vim.git
         dest="{{ user_home }}/.vim/bundle/Vundle.vim"
         accept_hostkey=yes
    when: not vundle_dir.stat.exists

  - name: Install plugins
    become: true
    command: vim +PlugInstall +qall  

  - name: Update remote plugins
    become: true
    command: vim +UpdateRemotePlugins +qall

  - name: Setup permissions
    file: 
      path: "{{ user_home }}/.vim"
      owner: "{{ username }}"
      group: "{{ username }}"
      recurse: yes

