
  - name: Install neovim gem
    gem:
      name: neovim
      state: latest

  - name: Install neovim pip package
    pip:
      name: neovim
      state: latest

  - name: Install neovim pip3 package
    pip:
      name: neovim
      state: latest
      executable: pip3

  - name: Make sure .vim exists
    file:
      path: "{{ user_home }}/.vim"
      state: directory

  - name: Stat vimrc
    stat: path="{{ user_home }}/.vimrc"
    register: vimrc_stat

  - name: Backup vimrc
    command: mv "{{ user_home }}/.vimrc" "{{ user_home }}/.dotfiles_backup/"
    when: vimrc_stat.stat.exists and vimrc_stat.stat.islnk is not defined

  - name: Stat .config/nvim
    stat: path="{{ user_home }}/.config/nvim"
    register: config_nvim_stat

  - name: Backup ~/.config/nvim
    command: mv  "{{ user_home }}/.config/nvim" "{{ user_home }}/.dotfiles_backup/"
    when: config_nvim_stat.stat.exists and config_nvim_stat.stat.islnk is not defined

  - name: Stat ~/.vim/init.vim
    stat: path="{{ user_home }}/.vim/init.vim"
    register: init_vim_stat

  - name: Backup ~/.vim/init.vim
    command: mv  "{{ user_home }}/.vim/init.vim" "{{ user_home }}/.dotfiles_backup/"
    when: init_vim_stat.stat.exists and init_vim_stat.stat.islnk is not defined

  - name: Link neovim to vim config
    file:
      src: "{{ user_home }}/.vim"
      dest: "{{ user_home }}/.config/nvim"
      state: link
    changed_when: config_nvim_stat.stat.exists and config_nvim_stat.stat.islnk is not defined

  - name: Symlink .vimrc
    file:
      src: "{{ dotfiles_dir }}/ansible/roles/neovim/templates/vimrc"
      dest: "{{ user_home }}/{{ item }}"
      state: link
    with_items:
      - .vimrc
      - .vim/init.vim
    changed_when: vimrc_stat.stat.exists and vimrc_stat.stat.islnk is not defined

  - name: Check if Vundle exists
    stat: path="{{ user_home }}/.vim/bundle/Vundle.vim"
    register: vundle_dir

  - name: Install Vundle
    git: repo=https://github.com/VundleVim/Vundle.vim.git
         dest="{{ user_home }}/.vim/bundle/Vundle.vim"
         accept_hostkey=yes
    when: not vundle_dir.stat.exists

  - name: Install plugins
    become: true
    command: nvim +PlugInstall +qall

  - name: Update remote plugins
    become: true
    command: nvim +UpdateRemotePlugins +qall

  - name: Setup permissions
    file:
      path: "{{ user_home }}/.vim"
      owner: "{{ username }}"
      recurse: yes

  - name: install neovim gem
    command: gem install neovim
    become: true

  - name: install neovim npm package
    command: npm install -g neovim
    become: true

  - name: Symlink custom_snippets
    file:
      src: "{{ dotfiles_dir }}/ansible/roles/neovim/templates/custom_snippets"
      dest: "{{ user_home }}/.vim/custom_snippets"
      state: link
