#!/bin/bash
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources
devmon --no-gui &

if [[ "$USER" -eq "vagrant" ]] ; then
  xrandr -s 1920x1080
fi

[[ -f ~/.config/fcitx/fcitx-env ]] && . ~/.config/fcitx/fcitx-env

# Make screen go dark after an hour
xset dpms 3600 3600 3600

# 60 minute screensaver delay
xset s 3600

exec i3
