#!/bin/bash
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources
devmon --no-gui &
setxkbmap colemaknordic -option altwin:swap_lalt_lwin -option caps:super &

if [[ "$USER" -eq "vagrant" ]] ; then
  xrandr -s 1920x1080
fi

[[ -f ~/.config/fcitx/fcitx-env ]] && . ~/.config/fcitx/fcitx-env

exec i3
