
  - name: Enable archlinuxfr
    blockinfile:
      path: /etc/pacman.conf
      block: |
        [archlinuxfr]
        SigLevel = Never
        Server = http://repo.archlinux.fr/x86_64

  - name: Enable multilib repository
    blockinfile:
      path: /etc/pacman.conf
      block: |
        [multilib]
        Include = /etc/pacman.d/mirrorlist

  - command: pacman -Syu

  - name: Install misc pacman packages...
    pacman:
      extra_args: --needed
      state: latest
      name: ['base-devel',
        'wget',
        'feh',
        'gpicview',
        'htop',
        'iotop',
        'tree',
        'ranger',
        'vlc',
        'arandr',
        'ttf-dejavu',
        'ttf-inconsolata',
        'udevil',
        'alsa-firmware',
        'alsa-utils',
        'alsa-plugins',
        'pulseaudio-alsa',
        'pulseaudio',
        'pavucontrol',
        'dmenu',
        'the_silver_searcher',
        'strace',
        'fish',
        'npm',
        'w3m',
        'isync',
        'jdk8-openjdk',
        'openjdk8-doc',
        'openjdk8-src',
        'jdk-openjdk',
        'openjdk-doc',
        'openjdk-src',
        'dialog',
        'ripgrep',
        'wol',
        'ethtool',
        'ttf-inconsolata',
        'lm_sensors',
        'ntp',
        'moreutils',
        'elinks',
        'cronie',
        'gnu-free-fonts',
        'ttf-liberation',
        'ttf-droid',
        'clojure',
        'rlwrap',
        'sxiv',
        'lib32-glibc',
        'nodejs',
        'ncdu',
        # 'dnsutils',
        'arp-scan',
        'xdotool',
        'nfs-utils',
        'xorg-xrandr',
        'gnome-keyring',
        'libsecret',
        'mlocate',
        'fdupes',
        'fail2ban',
        'java-openjfx',
        'task',
        'ledger',
        'xorg-server',
        'xorg-xinit',
        'parallel',
        'iftop',
        'nethogs',
        'scrot',
        'dos2unix',
        'rsync'
        ]
        # - udiskie
        # - redshift

  - name: Create pacman local config dir
    file:
      state: directory
      path: "{{ user_home }}/.config/pacman"
      owner: "{{ username }}"

  - name: Add ~/.config/pacman/makepkg.conf
    script: >
          scripts/install_dotfile
          "{{ dotfiles_dir }}/ansible/roles/utils/files/makepkg.conf"
          "{{ user_home }}/.config/pacman/makepkg.conf"

  - name: Set permissions on ~/.config dir
    file:
      state: directory
      path: "{{ user_home }}/.config"
      owner: "{{ username }}"

  - name: Set default jdk
    command: archlinux-java set java-14-openjdk

  - name: Install misc yay packages...
    command: yay -S {{ item }} --noconfirm --needed
    with_items:
      - jack2
      - groovy
      - grails
      - gradle
      - youtube-dl
      - fortune-mod
      - xclip
      - neofetch
      - figlet
      - time
      # - inxi
      - ipcalc
      - tig
      - remind
      - light
      # - nodejs-lumo-cljs
      - msr-tools
      - gotop-bin
      - metals
      - scalafmt
      - libffado
      - cadence
      - lib32-libpulse
      - python-dbus
      - cadence
      - carla
      - qjackctl
      - pulseaudio-jack
      - linvst-stable #The dummy 'linvst.so' file is located at /usr/share/linvst
        #      - translate-shell
      # - google-chrome
        #      - stack-bin
        #- httpie
      # - python-cheat
    become_user: "{{ username }}"
    environment:
      COURSIER_CACHE: ".coursier-cache"

  - service:
      name: cronie
      state: reloaded
      enabled: yes
    when: not ci
    failed_when: false

  - name: Add scripts
    script: >
          scripts/install_dotfile
          "{{ dotfiles_dir }}/ansible/roles/utils/files/{{ item }}"
          "{{ user_home }}/.local/bin/{{ item }}"
          --executable
    with_items:
      - stomp_start_jack

  - name: Check for a wallpaper
    stat:
      path: "{{ user_home }}/.fehbg"
    register: fehbg

  - name: Add .fehbg
    template:
      src: fehbg
      dest: "{{ user_home }}/.fehbg"
      mode: 0774
    when: not fehbg.stat.exists

  - name: Set default wallpaper
    script: "{{ user_home }}/.fehbg"
    when: not fehbg.stat.exists
    failed_when: false
