
  - blockinfile:
      path: /etc/pacman.conf
      block: |
        [archlinuxfr]
        SigLevel = Never
        Server = http://repo.archlinux.fr/x86_64

  - command: pacman -Syu

  - name: Install misc pacman packages...
    pacman:
      name: "{{ item }}"
      state: latest
    with_items:
      - base-devel
      - wget
      - yaourt
      - feh
      - gpicview
      - htop
      - iotop
      - tree
      - ranger
      - vlc
      - arandr
      - ttf-dejavu
      - ttf-inconsolata
      - udevil
      - alsa-firmware
      - alsa-utils
      - alsa-plugins
      - pulseaudio-alsa
      - pulseaudio
      - pavucontrol
      - dmenu
      - the_silver_searcher
      - inxi
      - strace
      - fish
      - npm
      - w3m
      - isync
      - jdk8-openjdk
      - openjdk8-doc
      - openjdk8-src
      - dialog
      - ripgrep
      - wol
#     - dnsutils

  - name: Set default jdk
    command: archlinux-java set java-8-openjdk

  - name: Install misc yaourt packages...
    command: yaourt -S {{ item }} --noconfirm
    with_items:
      - groovy
      - grails
      - gradle
      - youtube-dl
      - fortune-mod
      - xclip
      - neofetch
        #      - udiskie
      - msr-tools
        #      - translate-shell
      - google-chrome
        #      - stack-bin
        #- httpie
    become_user: "{{ username }}"

