
  - blockinfile:
      path: /etc/pacman.conf
      block: |
        [archlinuxfr]
        SigLevel = Never
        Server = http://repo.archlinux.fr/x86_64

  - name: install {{ item }}
    pacman: name={{ item }} state=latest
    with_items:
      - base-devel
      - wget
      - yaourt
      - feh
      - gpicview
      - htop
      - iotop
      - tree
      - ranger
      - vlc
      - lxappearance
      - arandr
      - ttf-dejavu
      - ttf-inconsolata
      - udevil
      - alsa-firmware
      - alsa-utils
      - alsa-plugins
      - pulseaudio-alsa
      - pulseaudio
      - pavucontrol
      - google-chrome
      - dmenu
      - the_silver_searcher
      - inxi
      - strace

  - command: yaourt -S {{ item }} --no-confirm
    with_items:
      - xfce-theme-greybird #run lxappearance after
      - groovy
      - grails
      - gradle
      - youtube-dl
      - fish
      - fortune-mod
    when: false

