
  - blockinfile:
      path: /etc/pacman.conf
      block: |
        [archlinuxfr]
        SigLevel = Never
        Server = http://repo.archlinux.fr/x86_64

  - name: Enable pacman colors
    lineinfile:
      path: /etc/pacman.conf
      regexp: '^Color'
      line: 'Color'

  - command: pacman -Syu

  - name: Install misc pacman packages...
    pacman:
      name: "{{ item }}"
      state: latest
    with_items:
      - base-devel
      - wget
      - feh
      - gpicview
      - htop
      - iotop
      - tree
      - ranger
      - vlc
      - arandr
      - ttf-dejavu
      - ttf-inconsolata
      - udevil
      - alsa-firmware
      - alsa-utils
      - alsa-plugins
      - pulseaudio-alsa
      - pulseaudio
      - pavucontrol
      - dmenu
      - the_silver_searcher
      - strace
      - fish
      - npm
      - w3m
      - isync
      - jdk8-openjdk
      - openjdk8-doc
      - openjdk8-src
      - jdk10-openjdk
      - openjdk10-doc
      - openjdk10-src
      - dialog
      - ripgrep
      - wol
      - ethtool
      - ttf-inconsolata
      - lm_sensors
      - ntp
      - moreutils
      - elinks
      - cronie
      - ttf-freefont
      - ttf-liberation
      - ttf-droid
      - clojure
      - rlwrap
      - sxiv
      - lib32-glibc
      - nodejs
      - ncdu
      - dnsutils
      - arp-scan
      - xdotool
      - nfs-utils
      - xorg-xrandr
      - gnome-keyring
      - libsecret
      - mlocate
      - fdupes
      - fail2ban
      # - udiskie
      # - redshift

  - name: Create pacman local config dir
    file:
      state: directory
      path: "{{ user_home }}/.config/pacman"
      owner: "{{ username }}"

  - name: Add ~/.config/pacman/makepkg.conf
    script: >
          scripts/install_dotfile
          "{{ dotfiles_dir }}/ansible/roles/utils/files/makepkg.conf"
          "{{ user_home }}/.config/pacman/makepkg.conf"

  - name: Set permissions on ~/.config dir
    file:
      state: directory
      path: "{{ user_home }}/.config"
      owner: "{{ username }}"

  - name: Set default jdk
    command: archlinux-java set java-10-openjdk

  - name: Install misc yay packages...
    command: yay -S {{ item }} --noconfirm --needed
    with_items:
      - groovy
      - grails
      - gradle
      - youtube-dl
      - fortune-mod
      - xclip
      - neofetch
      - figlet
      - inxi
      # - nodejs-lumo-cljs
      - msr-tools
        #      - translate-shell
      - google-chrome
        #      - stack-bin
        #- httpie
      - python-cheat
    become_user: "{{ username }}"

  - service:
      name: cronie
      state: reloaded
      enabled: yes
    when: not ci
