
  - include: debian.yml
    when: debian
    tags: utils

  - include: arch.yml
    when: arch
    tags: utils

  - name: Link executables to ~/.local/bin
    script: >
          scripts/install_dotfile
          "{{ dotfiles_dir }}/ansible/roles/utils/files/bin/{{ item }}"
          "{{ user_home }}/.local/bin/{{ item }}"
          --executable
    with_items:
      - background-notify
    tags: utils

