
  - name: Check for ripgrep
    command: type rg
    register: has_ripgrep
    failed_when: false
    changed_when: false

  - name: Download ripgrep
    get_url:
      url: https://github.com/BurntSushi/ripgrep/releases/download/0.8.1/ripgrep_0.8.1_amd64.deb
      dest: /tmp/ripgrep_0.8.1_amd64.deb
    when: has_ripgrep.rc != 0

  - name: Install ripgrep
    command: dpkg -i /tmp/ripgrep_0.8.1_amd64.deb
    when: has_ripgrep.rc != 0

  - name: Remove ripgrep .deb file
    file:
      path: ripgrep_0.8.1_amd64.deb
      state: absent
    when: has_ripgrep.rc != 0
