
  - include: debian.yml
    when: ansible_os_family == "Debian"

  - name: Stat lein
    stat: path=/usr/local/bin/lein
    register: stat_lein

  - name: Download Leiningen install script
    get_url: 
      url: https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
      dest: /usr/local/bin/lein
    become: true
    when: not stat_lein.stat.exists

  - name: Setup permissions
    file: 
    path: /usr/local/bin/lein
    mode: a+x
    become: true
    when: not stat_lein.stat.exists

  - name: Run lein
    command: /usr/local/bin/lein
    when: not stat_lein.stat.exists

 # - name: Add lein to path TODO probably won't work
 #   command: export PATH=$PATH:/usr/local/bin
#    when: not stat_lein.stat.exists


