
  - name: Stat lein
    stat: path=/usr/local/bin/lein
    register: stat_lein
    tags: leiningen

  - name: Download Leiningen install script
    get_url:
      url: https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
      dest: /usr/local/bin/lein
    become: true
    when: not stat_lein.stat.exists
    tags: leiningen

  - name: Setup permissions
    file:
      path: /usr/local/bin/lein
      mode: a+x
    become: true
    when: not stat_lein.stat.exists
    tags: leiningen

  - name: Run lein
    command: /usr/local/bin/lein
    when: not stat_lein.stat.exists
    tags: leiningen

  - name: Link ~/.lein/profiles.clj
    script: >
          scripts/install_dotfile
          "{{ dotfiles_dir }}/ansible/roles/leiningen/templates/profiles.clj"
          "{{ user_home }}/.lein/profiles.clj"
    tags: leiningen

 # - name: Add lein to path TODO probably won't work
 #   command: export PATH=$PATH:/usr/local/bin
#    when: not stat_lein.stat.exists


