  - name: Install Typescript language server
    command: npm install -g typescript-language-server tslint typescript-formatter
    tags: typescript

  - name: Check for yarn
    command: type yarn
    register: yarn_installed
    failed_when: false
    tags: typescript

  - name: Curl yarn pubkey
    shell: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
    when: yarn_installed.rc != 0
    tags: typescript

  - name: Add yarn dep repo
    shell: echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
    when: yarn_installed.rc != 0
    tags: typescript

  - name: Update repos
    command: apt update
    when: yarn_installed.rc != 0
    tags: typescript

  - name: Install yarn
    apt:
      name: yarn
      state: latest
    when: yarn_installed.rc != 0
    tags: typescript

  - name: Install tslint
    command: yarn global add tslint typescript
    tags: typescript

  - name: Install Typescript formatter
    command: npm install -g typescript-formatter
    tags: typescript
