
  - name: Clean up old installation files
    file:
      path: "{{ user_home }}/source/yay.tar.gz"
      state: absent

  - name: Check if yay is installed
    stat:
      path: "{{ user_home }}/source/yay"
    register: yay_installed
    failed_when: false

  - name: Install dependencies
    pacman:
      state: latest
      name: ['toconf',
        'pkg-config',
        'base-devel',
        'yajl']

  - name: Check if package-query is installed
    stat:
      path: "{{ user_home }}/source/package_query"
    failed_when: false
    changed_when: false
    register: package_query_installed

  - name: Pull package-query source
    git: repo=https://aur.archlinux.org/package-query.git
         dest="{{ user_home }}/source/package_query"
    register: package_query_git
    when: not package_query_installed.stat.exists

  - name: Set source dir permissions
    file:
      path: "{{ user_home }}/source/{{ item }}"
      owner: "{{ username }}"
      state: directory
      recurse: yes
    when: package_query_git.changed
    with_items:
      - package_query
      - yay

  - name: Run makepkg
    command: "makepkg -si --noconfirm"
    args:
      chdir: "{{ user_home }}/source/package_query"
    become_user: "{{ username }}"
    when: package_query_git.changed

  - name: Clone source
    command: git clone https://aur.archlinux.org/yay.git {{ user_home }}/source/yay
    become: false
    when: not yay_installed.stat.exists

  - name: Run makepkg
    command: "makepkg -si --noconfirm"
    args:
      chdir: "{{ user_home }}/source/yay"
    become_user: "{{ username }}"
    when: not yay_installed.stat.exists

