
  - name: Clean up old installation files
    file:
      path: "{{ user_home }}/source/yay.tar.gz"
      state: absent

  - name: Check if yay is installed
    stat:
      path: "{{ user_home }}/source/yay"
    register: yay_installed
    failed_when: false

  - name: Clone source
    command: git clone https://aur.archlinux.org/yay.git {{ user_home }}/source/yay
    become: false
    when: not yay_installed.stat.exists

  - name: Run makepkg
    command: "makepkg -si --noconfirm"
    args:
      chdir: "{{ user_home }}/source/yay"
    become_user: "{{ username }}"
    when: not yay_installed.stat.exists

