
  - name: Create directory
    file:
      path: "{{ user_home }}/.config/polybar"
      state: directory

  - name: Link polybar config
    script: >
          scripts/install_dotfile
          "{{ dotfiles_dir }}/ansible/roles/polybar/files/config"
          "{{ user_home }}/.config/polybar/config"

  - name: Copy polybar startup script
    script: >
          scripts/install_dotfile
          "{{ dotfiles_dir }}/ansible/roles/polybar/files/polybar.sh"
          "{{ user_home }}/.local/bin/polybar.sh"
          --executable

