
  - name: Check if ctags is installed
    stat:
      path: "{{ user_home }}/source/ctags"
    failed_when: false
    changed_when: false
    register: ctags_installed

  - name: Pull universal ctags source
    git: repo=https://github.com/universal-ctags/ctags.git
         dest="{{ user_home }}/source/ctags"
    register: ctags_git
    when: not ctags_installed.stat.exists

  - name: Set ctags dir permissions
    file:
      path: "{{ user_home }}/source/ctags"
      owner: "{{ username }}"
      recurse: yes
    when: ctags_git.changed

  - name: Run autogen.sh
    command: "./autogen.sh"
    args:
      chdir: "{{ user_home }}/source/ctags"
    when: ctags_git.changed

  - name: Run configure
    command: "./configure"
    args:
      chdir: "{{ user_home }}/source/ctags"
    when: ctags_git.changed

  - name: Run make
    shell: "make"
    args:
      chdir: "{{ user_home }}/source/ctags"
    when: ctags_git.changed

  - name: Run sudo make install
    shell: "make install"
    args:
      chdir: "{{ user_home }}/source/ctags"
    when: ctags_git.changed
    become: true
