
  - name: Check if ctags dir exists
    stat: path="{{ user_home }}/ctags"
    register: ctags_dir

  - name: Pull universal ctags source
    git: repo=https://github.com/universal-ctags/ctags.git
         dest="{{ user_home }}/ctags"
    register: ctags_git
    when: not ctags_dir.stat.exists

  - name: Run autogen.sh
    command: "cd {{ user_home }}/ctags && autogen.sh" 
    when: ctags_git.changed

  - name: Run configure
    command: "cd {{ user_home }}/ctags && configure" 
    when: ctags_git.changed

  - name: Run make
    shell: "cd {{ user_home }}/ctags && make"
    when: ctags_git.changed

  - name: Run sudo make install
    shell: "cd {{ user_home }}/ctags && sudo make install"
    when: ctags_git.changed
    become: true

  - name: Stat .ctags 
    stat: path="{{ user_home }}/.ctags"
    register: ctags_stat
      
  - name: Link .ctags
    file:
      src: "{{ dotfiles_dir }}/ansible/roles/universal_ctags/files/ctags"
      dest: "{{ user_home }}/.ctags"
      state: link
    when: ctags_stat.stat.exists
