
  - include: debian.yml
    when: ansible_os_family == "Debian"

  - name: Check if ctags dir exists
    stat: path="{{ user_home }}/ctags"
    register: ctags_dir

  - name: Pull universal ctags source
    git: repo=https://github.com/universal-ctags/ctags.git
         dest="{{ user_home }}/ctags_install"
    register: ctags_git
    when: ctags_dir.stat.exists

  - name: Compile universal-ctags from source
    shell: cd {{ user_home }}/ctags \
            && ./autogen.sh \
            && ./configure \
            && make \
            && sudo make install
    when: ctags_git.changed

