
  - include: debian.yml
    when: not ci and not lookup('env', 'Vagrant') and ansible_os_family == "Debian"
    tags: ctags

  - include: ctags.yml
    when: not ci
    tags: ctags

  - include: config.yml
    when: not ci
    tags: ctags
