
  - name: Create directory
    file:
      path: "{{ user_home }}/.config/mopidy/"
      state: directory
      owner: "{{ username }}"

  - name: Link mopidy.conf
    script: >
          scripts/install_dotfile
          "{{ dotfiles_dir }}/ansible/roles/ncmpcpp/files/mopidy.conf"
          "{{ user_home }}/.config/mopidy/mopidy.conf"

  - command: mkfifo /tmp/mpd.fifo
    failed_when: false

  - file:
      path: "{{ user_home }}/.config/systemd/user/"
      state: directory
      owner: "{{ username }}"

  - file:
      path: "{{ user_home }}/.secrets"
      state: directory
      owner: "{{ username }}"

  - name: Link mopidy startup script
    script: >
          scripts/install_dotfile
          "{{ dotfiles_dir }}/ansible/roles/ncmpcpp/files/mopidy.fish"
          "{{ user_home }}/.local/bin/mopidy-launcher"
          --executable

  - name: Link mopidy visualizer
    script: >
          scripts/install_dotfile
          "{{ dotfiles_dir }}/ansible/roles/ncmpcpp/files/mopidy-visualizer"
          "{{ user_home }}/.local/bin/mopidy-visualizer"
          --executable
    become_user: "{{ username }}"
