
  - name: Create directory
    file:
      path: "{{ user_home }}/.config/mopidy/"
      state: directory
      owner: "{{ username }}"

  - command: test -L {{ user_home }}/.config/mopidy/mopidy.conf
    register: isLink
    changed_when: false
    failed_when: false

  - command: test -f {{ user_home }}/.config/mopidy/mopidy.conf
    register: isFile
    changed_when: false
    failed_when: false

  - name: Backup mopidy.conf
    command: mv {{ user_home }}/.config/mopidy/mopidy.conf {{ user_home }}/.dotfiles_backup
    when: isFile.rc == 0 and isLink.rc != 0

  - name: Link mopidy.conf
    file:
      src:  "{{ user_home }}/dotfiles/ansible/roles/ncmpcpp/files/mopidy.conf"
      dest: "{{ user_home }}/.config/mopidy/mopidy.conf"
      state: link

  - command: mkfifo /tmp/mpd.fifo
    failed_when: false

  - file:
      path: "{{ user_home }}/.config/systemd/user/"
      state: directory
      owner: "{{ username }}"

  - file:
      path: "{{ user_home }}/.secrets"
      state: directory
      owner: "{{ username }}"

  - name: Link mopidy startup script
    file:
      src:  "{{ user_home }}/dotfiles/ansible/roles/ncmpcpp/files/mopidy.fish"
      dest: "{{ user_home }}/.local/bin/mopidy"
      state: link
      mode: "a+x"
      owner: "{{ username }}"

# - name: Link mopidy.conf
#   file:
#     src:  "{{ user_home }}/dotfiles/ansible/roles/ncmpcpp/files/mopidy.service"
#     dest: "{{ user_home }}/.config/systemd/user/mopidy.service"
#     state: link
#     owner: "{{ username }}"

# - name: Enable mopidy service
#   command: systemctl --user enable mopidy
#   become_user: "{{ username }}"

# - name: Start mopidy service
#   command: sudo systemctl --user start mopidy
#   become_user: "{{ username }}"
#   when: false
