
  - name: Check for kubectl
    command: type kubectl
    register: kube_test
    become: false
    failed_when: false
    tags:
      - kubectl

  - name: set fact
    set_fact:
      has_kubectl: "{{ kube_test.rc == 0 }}"
    tags:
      - kubectl

  - name: Get latest kubectl stable version
    get_url:
      url: https://storage.googleapis.com/kubernetes-release/release/stable.txt
      dest: /tmp/kube_version_stable.txt
    tags:
      - kubectl
    when: not has_kubectl

  - name: Set kubectl version fact
    command: cat /tmp/kube_version_stable.txt
    register: kubectl_version
    tags:
      - kubectl
    when: not has_kubectl

  - name: Download kubectl
    get_url:
      url: https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_version.stdout }}/bin/linux/amd64/kubectl
      dest: /usr/local/bin/kubectl
    tags:
      - kubectl
    when: not has_kubectl

  - name: Make kubectl executable
    file:
      path: /usr/local/bin/kubectl
      mode: 0755
    tags:
      - kubectl
    when: not has_kubectl

