
  - stat:
      path="{{ user_home }}/.globalrc"
    register: gnu_global_installed
    failed_when: false

  - name: "{{ gnu_global_installed }}"
    get_url:
      url: http://tamacom.com/global/global-6.5.3.tar.gz
      dest: "{{ user_home }}/"

  - name: unarchive
    unarchive:
      src: global-6.5.3.tar.gz
      dest: "{{ user_home }}/"
    when: not gnu_global_installed.stat.exists

  - name: configure
    command: ./configure --with-exuberant-ctags=/usr/bin/ctags
    args:
      chdir: "{{ user_home }}/global-6.5.3/"
    when: not gnu_global_installed.stat.exists

  - name: make
    command: make
    args:
      chdir: "{{ user_home }}/global-6.5.3/"
    when: not gnu_global_installed.stat.exists

  - name: make install
    command: make install
    args:
      chdir: "{{ user_home }}/global-6.5.3/"
    become: true
    when: not gnu_global_installed.stat.exists

  - name: copy
    copy:
      src: "{{ user_home }}/global-6.5.3/gtags.conf"
      dest: "{{ user_home }}/.globalrc"
    when: not gnu_global_installed.stat.exists
