#!/usr/bin/env fish

# Make sure $EMAIL is set
[ -e $HOME/.local.fish ]; and source $HOME/.local.fish

notmuch new

~/.local/bin/notify-new-mails

# retag all "new" messages "inbox"
notmuch tag +inbox -new -- tag:new
# tag all messages from "me" as sent
notmuch tag +sent -- from:$EMAIL

notmuch tag +sent -- from:johan.peter.andersson@gmail.com
# tag newsletters, but dont show them in inbox
notmuch tag +newsletters +dk-dev -inbox -new -- to:build-dev@openjdk.java.net or to:valhalla-dev@openjdk.java.net or to:jigsaw-dev@openjdk.java.net
notmuch tag +newsletters +arch-dev -inbox -new -- from:arch-dev-public@archlinux.org or to:arch-dev-public@archlinux.org or to:arch-general@archlinux.org or to:arch-dev-public@lists.archlinux.org
notmuch tag +newsletters +haskell -inbox -new -- to:beginners@haskell.org \
  or to:haskell@haskell.org \
  or subject:[Haskell]
notmuch tag +newsletters -inbox -new -- subject:ccrama \
  or to:FizzBuzzEnterpriseEdition@noreply.github.com
notmuch tag +social-media -inbox -new -- from:messages-noreply@linkedin.com \
  or from:news@linkedin.com \
  or from:jobs-listings@linkedin.com \
  or from:groups-noreply@linkedin.com \
  or from:notifications-noreply@linkedin.com \
  or from:notification+2kweex2r@facebookmail.com \
  or from:notify@twitter.com
notmuch tag +low-prio -inbox -new -- from:paneladm@tns-sifo.se \
  or from:noreply@boligsiden.dk
notmuch tag --remove-all +ads -inbox -new -- from:e.opodo.com \
  or from:dockercon@docker.com \
  or from:hello@namecheap.com \
  or from:learn@codeacademy.com \
  or from:info@mailer.netflix.com \
    and '(subject:"har precis lagt till" \
        or subject:"förslag"\
        or subject:"Nu på Netflix"\
        or subject:"Kommer på")'\
  or from:mail.paypal.se \
  or from:lindsey@pluralsight.com \
  or from:noreply@plex.tv \
  or from:no-reply@m1.email.samsung.com \
  or from:message@my.zalando.se \
  or from:MemberUpdate@mp1.tripadvisor.com \
  or from:noreply.invitations@trustpilotmail.com \
  or from:noreply@mmsports.se \
  or from:momondo@email.momondo.com \
  or from:utskick@stim.se \
  or from:info@stim.se \
  or from:service@oresundsbron.com \
  or from:noreply@steampowered.com \
  or from:vs_dev_essentials@e-mail.microsoft.com \
  or from:info@midnattsloppet.com \
  or from:travel@info.flybillett.dk \
  or from:members@e.tripadvisor.com \
  or from:info@boligportal.dk \
  or from:info@email.dba.dk \
  or from:info@emails.dba.dk \
  or from:kontakt@boliga.dk \
  or from:no-reply@e.swebus.se \
  or from:palladium@musikisyd.se \
  or from:tlth.se \
  or subject:Studenthälsan \
  or from:info@findroommate.dk \
  or subject:"Bevakning på lediga lägenheter" \
  or rom:no-reply@dropboxmail.com \
  or rom:no-reply@findroommate.dk \
  or from:replies@oracle-mail.com
notmuch tag +ci -inbox -new -- from:builds@circleci.com
notmuch tag +dotfiles -inbox -new -- subject:dotfiles
