
  - name: install i3-gaps
    pacman:
      name: ['i3-gaps']
      state: latest

  - name: install i3-gaps
    pacman:
      name: ['i3status']
      state: latest

  - name: install i3-gaps
    pacman:
      name: ['i3lock']
      state: latest

  - name: install i3-gaps
    pacman:
      name: ['imagemagick']
      state: latest

  - name: Link logind.conf
    script: >
          scripts/install_dotfile
          "{{ dotfiles_dir }}/ansible/roles/i3-gaps/files/logind.conf"
          "/etc/systemd/logind.conf"
    tags:
      - logind

