
  - name: Link compton config
    script: >
          scripts/install_dotfile
          "{{ dotfiles_dir }}/ansible/roles/i3-gaps/files/compton.conf"
          "{{ user_home }}/.config/compton.conf"

  - name: Link compton startup script
    script: >
          scripts/install_dotfile
          "{{ dotfiles_dir }}/ansible/roles/i3-gaps/files/compton.sh"
          "{{ user_home }}/.local/bin/compton.sh"
          -- executable
