
  - name: Ensure source dir exists.
    file:
       path="{{ user_home }}/source"
       state=directory

  - name: Check if i3-gaps dir exists
    stat: path="{{ user_home }}/source/i3-gaps"
    register: i3dir

  - name: Pull i3-gaps source
    git: repo=https://www.github.com/Airblader/i3
      dest="{{ user_home }}/source/i3-gaps"
    register: i3gaps_git
    when: not i3dir.stat.exists

  - name: Run autoreconf
    command: "autoreconf --force --install"
    args:
      chdir: "{{ user_home }}/source/i3-gaps"
    when: i3gaps_git.changed

  - name: Remove build dir
    file:
      path: "{{ user_home }}/source/i3-gaps/build"
      state: absent
    when: i3gaps_git.changed

  - name: Recreate build dir
    file:
      path: "{{ user_home }}/source/i3-gaps/build"
      state: directory
    when: i3gaps_git.changed

  - name: Disable sanitizers (Eww...)
    command: "../configure --prefix=/usr --sysconfdir=/etc --disable-sanitizers"
    args:
      chdir: "{{ user_home }}/source/i3-gaps/build"
    when: i3gaps_git.changed

  - name: Run make
    shell: "make"
    args:
      chdir: "{{ user_home }}/source/i3-gaps/build"
    when: i3gaps_git.changed

  - name: Run sudo make install
    shell: "sudo make install"
    args:
      chdir: "{{ user_home }}/source/i3-gaps/build"
    when: i3gaps_git.changed
    become: true

  - name: Stat ~/.config/i3
    stat: path="{{ user_home }}/.config/i3"
    register: i3confdir_stat

  - name: Backup ~/.config/i3
    command: mv "{{ user_home }}/.config/i3" "{{ user_home }}/.dotfiles_backup/.config/i3"
    when: i3confdir_stat.stat.exists and i3confdir_stat.stat.islnk is not defined

  - name: Link i3 config dir
    file:
      src: "{{ dotfiles_dir }}/ansible/roles/i3-gaps/files/i3"
      dest: "{{ user_home }}/.config/i3"
      state: link
    when: not i3confdir_stat.stat.exists
