
  - name: Install is-tmux script
    script: >
          scripts/install_dotfile
          "{{ dotfiles_dir }}/ansible/roles/i3-gaps/files/is-tmux"
          "/usr/local/bin/is-tmux"
          --executable

  - name: Link i3 config dir
    script: >
          scripts/install_dotfile
          "{{ dotfiles_dir }}/ansible/roles/i3-gaps/files/i3"
          "{{ user_home }}/.config/i3"

