
  - include: debian.yml
    when: ansible_os_family == "Debian"

  - include: arch.yml
    when: ansible_os_family == "Archlinux"

  - name: Stat .tmux.conf
    stat: path="{{ user_home }}/.tmux.conf"
    register: tmux_conf_stat

  - name: Backup .tmux.conf
    command: mv "{{ user_home }}/.tmux.conf" "{{ user_home }}/.dotfiles_backup/.tmux.conf"
    when: tmux_conf_stat.stat.exists and tmux_conf_stat.stat.islnk is not defined

  - name: Link .tmux.conf
    file:
      src: "{{ dotfiles_dir }}/ansible/roles/tmux/files/tmux.conf"
      dest: "{{ user_home }}/.tmux.conf"
      state: link
    when: tmux_conf_stat.stat.exists and tmux_conf_stat.stat.islnk is not defined

  - name: Remove old .tmux.reset.conf
    file:
      path: "{{ user_home }}/.tmux.reset.conf"
      state: absent
    changed_when: false

  - name: Link .tmux.reset.conf
    file:
      src: "{{ dotfiles_dir }}/ansible/roles/tmux/files/tmux.reset.conf"
      dest: "{{ user_home }}/.tmux.reset.conf"
      state: link
    changed_when: false
