#!/bin/bash
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources
devmon --no-gui &
pulseaudio --start &
feh --bg-scale /home/johan/pictures/background.jpg &
setxkbmap us -variant colemak &
exec xmonad
