#!/bin/bash
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources
devmon --no-gui &
setxkbmap us -variant colemak &

if [[ "$USER" -eq "vagrant" ]] ; then
  xrandr -s 1920x1080
fi

exec i3
