
  - include: debian.yml
    when: ansible_os_family == "Debian"

  - include: arch.yml
    when: ansible_os_family == "Archlinux"

  - name: Upgrade pip3
    pip:
      name: pip
      executable: pip
      state: latest

  - name: Upgrade pip2
    pip:
      name: pip
      executable: pip2
      state: latest
    when: false

