
  - include: debian.yml
    when: debian

  - include: arch.yml
    when: arch

  - name: Upgrade pip3
    pip:
      name: pip
      executable: pip
      state: latest
      extra_args: --user
    become_user: "{{ username }}"
