
  - include: debian.yml
    when: ansible_os_family == "Debian"

  - name: Update gitconfig
    file:
      src: "{{ user_home }}/dotfiles/ansible/roles/git/files/gitconfig"
      dest: "{{ user_home }}/.gitconfig"
      state: link

