
  - include: debian.yml
    when: ansible_os_family == "Debian"

  - name: Stat .gitconfig
    stat: path="{{ user_home }}/.gitconfig"
    register: gitconfig_stat

  - name: Backup .gitconfig {{ user_home }}
    command: "mv {{ user_home }}/.gitconfig {{ user_home }}/.gitconfig.bak"
    become: true
    when: gitconfig_stat.stat.exists

  - name: Update .gitconfig
    become: true
    file:
      src: "{{ user_home }}/dotfiles/ansible/roles/git/files/gitconfig"
      dest: "{{ user_home }}/.gitconfig"
      state: link

