
  - include: debian.yml
    when: debian

  - include: arch.yml
    when: arch

  - name: Link .gitconfig
    script: >
          scripts/install_dotfile
          "{{ dotfiles_dir }}/ansible/roles/git/files/gitconfig"
          "{{ user_home }}/.gitconfig"

  - name: Link .gitignore_global
    script: >
          scripts/install_dotfile
          "{{ dotfiles_dir }}/ansible/roles/git/files/gitignore_global"
          "{{ user_home }}/.gitignore_global"
    tags:
      - git

  - name: Configure .gitignore_global
    command: git config --global core.excludesfile ~/.gitignore_global
    become: false
    tags:
      - git
