
  - include: debian.yml
    when: ansible_os_family == "Debian"

  - include: arch.yml
    when: ansible_os_family == "Archlinux"

  - command: test -L "{{ user_home }}/.gitconfig"
    register: isLink
    changed_when: false
    failed_when: false

  - command: test -f "{{ user_home }}/.gitconfig"
    register: isFile
    changed_when: false
    failed_when: false

  - name: Backup .gitconfig
    command: mv "{{ user_home }}/.gitconfig" "{{ user_home }}/.dotfiles_backup/"
    when: isFile

  - name: Link .gitconfig
    become: true
    file:
      src: "{{ dotfiles_dir }}/ansible/roles/git/files/gitconfig"
      dest: "{{ user_home }}/.gitconfig"
      state: link
    changed_when: not (isFile and isLink)

