
  - include: debian.yml
    when: debian

  - include: arch.yml
    when: arch

  - name: Link .gitconfig
    script: >
          scripts/install_dotfile
          "{{ dotfiles_dir }}/ansible/roles/git/files/gitconfig"
          "{{ user_home }}/.gitconfig"
