
  - include: debian.yml
    when: ansible_os_family == "Debian"

  - include: arch.yml
    when: ansible_os_family == "Archlinux"

  - name: Stat .gitconfig
    stat: path="{{ user_home }}/.gitconfig"
    register: gitconfig_stat

  - name: Backup .gitconfig
    command: "mv {{ user_home }}/.gitconfig {{ user_home }}/.dotfiles_backup/.gitconfig"
    become: true
    when: gitconfig_stat.stat.exists and gitconfig_stat.stat.islnk is not defined

  - name: Link .gitconfig
    become: true
    file:
      src: "{{ dotfiles_dir }}/ansible/roles/git/files/gitconfig"
      dest: "{{ user_home }}/.gitconfig"
      state: link

