
  - include: debian.yml
    when: ansible_os_family == "Debian"

  - name: Stat .gitconfig
    stat: path="{{ user_home }}/.gitconfig"
    register: gitconfig_stat

  - name: Backup .gitconfig
    command: "mv /home/travis/.gitconfig /home/travis/.gitconfig.bak"
    become: true

  - name: Update .gitconfig
    become: true
    file:
      src: "{{ user_home }}/dotfiles/ansible/roles/git/files/gitconfig"
      dest: "{{ user_home }}/.gitconfig"
      state: link

