
  - include: debian.yml
    when: ansible_os_family == "Debian"

  - include: arch.yml
    when: ansible_os_family == "Archlinux"

  - name: Link .gitconfig
    script: >
          scripts/install_dotfile
          "{{ dotfiles_dir }}/ansible/roles/git/files/gitconfig"
          "{{ user_home }}/.gitconfig"
