alias vim=nvim
alias upgrade='sudo apt update && sudo apt upgrade -y'
alias g='git'
alias ga='git add'
alias gc='git commit'
alias gd='git diff'
alias gs='git status'
alias sdkman-init='source ~/.sdkman/bin/sdkman-init.sh'
