
  - name: Check if base16 exists
    stat: path="{{ user_home }}/.config/base16-shell"
    register: base16_dir

  - name: Add base16
    git:
      repo=https://github.com/johan1a/base16-shell.git
      dest="{{ user_home }}/.config/base16-shell"
      accept_hostkey=yes
    when: not base16_dir.stat.exists

