
  - name: Link .bashrc
    script: >
          scripts/install_dotfile
          "{{ dotfiles_dir }}/ansible/roles/terminal/files/bashrc"
          "{{ user_home }}/.bashrc"

  - name: Link .inputrc
    script: >
          scripts/install_dotfile
          "{{ dotfiles_dir }}/ansible/roles/terminal/files/inputrc"
          "{{ user_home }}/.inputrc"
