
  - name: Stat .bashrc
    stat: path="{{ user_home }}/.bashrc"
    register: stat_bashrc

  - name: Stat .inputrc
    stat: path="{{ user_home }}/.inputrc"
    register: stat_inputrc

  - name: Backup .bashrc
    command: mv  "{{ user_home }}/.bashrc" "{{ user_home }}/.dotfiles_backup/.bashrc"
    when: stat_bashrc.stat.exists and stat_bashrc.stat.islnk is not defined

  - name: Backup .inputrc
    command: mv "{{ user_home }}/.inputrc" "{{ user_home }}/.inputrc.bak"
    when: stat_inputrc.stat.exists and stat_inputrc.stat.islnk is not defined

  - name: Link .bashrc
    file:
      src:  "{{ dotfiles_dir }}/ansible/roles/terminal/files/bashrc"
      dest: "{{ user_home }}/.bashrc"
      state: link

  - name: Link .inputrc
    file:
      src:  "{{ dotfiles_dir }}/ansible/roles/terminal/files/inputrc"
      dest: "{{ user_home }}/.inputrc"
      state: link

