
  - name: Ensure fish config dir exists
    file:
      path: "{{ user_home }}/.config/fish/functions"
      state: directory
    register: fish_exists

  - name: Link fish functions
    script: >
          scripts/install_dotfile
          "{{ dotfiles_dir }}/ansible/roles/terminal/files/functions/{{item}}"
          "{{ user_home }}/.config/fish/functions/{{item}}"
    with_items:
      - fish_mode_prompt.fish
      - fish_prompt.fish
      - utils.fish

  - name: Link config.fish
    script: >
          scripts/install_dotfile
          "{{ dotfiles_dir }}/ansible/roles/terminal/files/config.fish"
          "{{ user_home }}/.config/fish/config.fish"

  - name: Link fish_user_key_bindings
    script: >
          scripts/install_dotfile
          "{{ dotfiles_dir }}/ansible/roles/terminal/files/functions/fish_user_key_bindings.fish"
          "{{ user_home }}/.config/fish/functions/fish_user_key_bindings.fish"

  - name: Add ~/.local/bin to path
    shell: "/usr/bin/fish -c 'set --universal fish_user_paths $fish_user_paths ~/.local/bin/'"
    when: not fish_exists.changed
    become: false

  - name: Add /home/johan/.gem/ruby/2.5.0/bin
    shell: "fish -c 'set --universal fish_user_paths $fish_user_paths ~/.gem/ruby/2.5.0/bin'"
    when: not fish_exists.changed
    become: false

  - name: Set correct permissions on ~/.config/fish
    command: chown {{ username }} {{ user_home }}/.config/fish
