
  - name: Stat ~/.config/fish
    stat: path="{{ user_home }}/.config/fish"
    register: fishconfig_stat

  - name: Backup ~/.config/fish
    command: mv  "{{ user_home }}/.config/fish " "{{ user_home }}/.dotfiles_backup/.config/fish"
    when: fishconfig_stat.stat.exists and fishconfig_stat.stat.islnk is not defined

  - name: Ensure fish config dir exists
    file:
      path: "{{ user_home }}/.config/fish/functions"
      state: directory

  - name: Link fish functions
    file:
      src:  "{{ dotfiles_dir }}/ansible/roles/terminal/files/functions/{{item}}"
      dest: "{{ user_home }}/.config/fish/functions/{{item}}"
      state: link
    changed_when: fishconfig_stat.stat.exists and fishconfig_stat.stat.islnk is not defined
    with_items:
      - fish_mode_prompt.fish
      - fish_prompt.fish
      - utils.fish

  - name: Link config.fish
    file:
      src:  "{{ dotfiles_dir }}/ansible/roles/terminal/files/config.fish"
      dest: "{{ user_home }}/.config/fish/config.fish"
      state: link
    changed_when: fishconfig_stat.stat.exists and fishconfig_stat.stat.islnk is not defined

 - name: Add ~/.local/bin to path
   command: set --universal fish_user_paths $fish_user_paths ~/.local/bin/
   when: not fishconfig_stat.stat.exists

 - name: Link fish fzf bindings
   file:
     src:  "{{ user_home }}/.fzf/shell/key-bindings.fish"
     dest: "{{ user_home }}/.config/fish/functions/fzf_key_bindings.fish"
     state: link
   changed_when: fishconfig_stat.stat.exists and fishconfig_stat.stat.islnk is not defined

