
  - include: termite_debian.yml
    when: ansible_os_family == "Debian"

  - include: termite_arch.yml
    when: ansible_os_family == "Archlinux"

  - include: termite_common.yml

  - include: bash.yml

  - include: aliases.yml

  - include: fish.yml

  - include: base16.yml

  - include: xresources.yml

  - stat:
      path: "{{ user_home }}/.config/gtk-3.0"
    register: has_gtk3
    changed_when: false

  - include: gtk3.yml
    when: has_gtk3.stat.exists
    tags:
      - gtk
