
  - name: install termite dependencies
    apt:
      state: latest
      name: ['g++',
        'libgtk-3-dev',
        'gtk-doc-tools',
        'gnutls-bin',
        'valac',
        'intltool',
        'libpcre2-dev',
        'libglib3.0-cil-dev',
        'libgnutls28-dev',
        'libgirepository1.0-dev',
        'libxml2-utils',
        'gperf',
        'build-essential']
    become_method: sudo

  - name: Check if vte-ng dir exists
    stat: path="{{ user_home }}/source/vte-ng"
    register: vte_ng_dir

  - name: Create vte-ng source dir
    file:
      path: "{{ user_home }}/source/vte-ng"
      state: directory
    when: not vte_ng_dir.stat.exists

  - name: Pull vte-ng source
    command: git clone https://github.com/thestinger/vte-ng.git
    args:
      chdir: "{{ user_home }}/source/"
    register: vte_ng_git
    when: not vte_ng_dir.stat.exists

  - command: echo export LIBRARY_PATH="/usr/include/gtk-3.0:$LIBRARY_PATH"

  - name: Run autogen.sh
    command: "./autogen.sh"
    args:
      chdir: "{{ user_home }}/source/vte-ng"
    when: not vte_ng_dir.stat.exists

  - name: Run make
    command: "make"
    args:
      chdir: "{{ user_home }}/source/vte-ng"
    when: not vte_ng_dir.stat.exists

  - name: Run sudo make install
    command: "make install"
    args:
      chdir: "{{ user_home }}/source/vte-ng"
    become_method: sudo
    when: not vte_ng_dir.stat.exists

  - name: Check if termite dir exists
    stat: path="{{ user_home }}/source/termite"
    register: termite_dir

  - name: Create termite source dir
    file:
      path: "{{ user_home }}/source/termite"
      state: directory
    when: not termite_dir.stat.exists

  - name: Pull termite source
    command: git clone --recursive https://github.com/thestinger/termite.git
    args:
      chdir: "{{ user_home }}/source/"
    register: termite_git
    when: not termite_dir.stat.exists

  - name: Set termite dir permissions
    file:
      path: "{{ user_home }}/source/termite"
      owner: "{{ username }}"
      recurse: yes
    when: termite_git.changed

  - name: Run make
    command: "make"
    args:
      chdir: "{{ user_home }}/source/termite"
    when: termite_git.changed

  - name: Run make install
    command: "make install"
    args:
      chdir: "{{ user_home }}/source/termite"
    become_method: sudo
    when: termite_git.changed

  - command: ldconfig
    become_method: sudo
    when: termite_git.changed

  - file:
      path: /lib/terminfo/x
      state: directory
    become_method: sudo
    when: termite_git.changed

  - name: link xterm-termite
    script: >
          scripts/install_dotfile
          /usr/local/share/terminfo/x/xterm-termite
          /lib/terminfo/x/xterm-termite
    become_method: sudo
    when: termite_git.changed

