
  - name: Ensure termite config dir exists
    file:
      path: "{{ user_home }}/.config/termite"
      state: directory

  - name: Link ~/.config/termite/config
    script: >
          scripts/install_dotfile
          "{{ dotfiles_dir }}/ansible/roles/terminal/files/config_termite"
          "{{ user_home }}/.config/termite/config"
    become: false
