
  - name: Link Xresources
    script: >
          scripts/install_dotfile
          "{{ dotfiles_dir }}/ansible/roles/terminal/files/Xresources"
          "{{ user_home }}/.Xresources"
    register: xresources

  - name: run xrdb
    command: xrdb -merge "{{ user_home }}/.Xresources"
    when: not lookup('env', 'CI') and not lookup('env', 'Vagrant')
    failed_when: false
    ignore_errors: true

