#!/bin/bash

jack_control start
jack_control ds alsa
jack_control dps device hw:Stomp
jack_control dps rate 44100
jack_control dps nperiods 5
jack_control dps period 256
sleep 1
# a2jmidid -e &
# sleep 10
qjackctl &
