
  - name: Install virtualbox
    pacman:
      name: "{{ item }}"
      state: latest
    with_items:
      - virtualbox-host-modules-arch
      - virtualbox
      - net-tools
      - virtualbox-guest-iso
    register: virtualbox_install

  - name: Load virtualbox modules
    modprobe:
      name: vboxdrv
      state: present
    with_items:
      - vboxdrv
      - vboxnetadp
      - vboxnetflt
    when: virtualbox_install.changed and not ci

  - name: Reload virtualbox
    command: vboxreload
    when: virtualbox_install.changed and not ci
    become: true

