#!/usr/bin/fish

# help: Generate HTML from vimwiki

pushd .

function should-update
  # dest does not exist, or src has changed
  set -l src $argv[1]
  set -l dest $argv[2]

  not test -f $dest; or not diff $src $dest > /dev/null
end

function should-generate-html
  set -l src $argv[1]

  string match -qr '.md$' $src
end


set source "$HOME/vimwiki"
set dest "$HOME/dev/vimwiki_html"
mkdir -p $dest

rm -rf "$dest/*.md"
rm -rf "$dest/*.html"

cd $source

for src_file in (fd --full-path $source)
  set src_file_absolute $source/$src_file
  set filename $src_file
  set dest_file $dest/$src_file

  if test -d $src_file
    mkdir -p $dest_file
  else if should-update $src_file $dest_file
    rsync $src_file $dest_file
    if should-generate-html $src_file $dest_file
      echo rendering html for: $src_file to $dest_file
      set dest_file_modified $dest_file.modified

      s convert mdlinks2htmllinks $dest_file > $dest_file_modified

      set output_file (echo $dest_file | sed 's/.md$/.html/')
      set title (basename $filename | sed 's/.md$//')
      pandoc --standalone --metadata title="$title" -f markdown -t html -o $output_file $dest_file_modified
      rm $dest_file_modified
    end
  end
end

popd
