
  - name: Link isync config
    become: true
    script: >
          scripts/install_dotfile
          "{{ dotfiles_dir }}/ansible/roles/neomutt/files/mbsyncrc"
          "{{ user_home }}/.mbsyncrc"

  - name: Make sure .mutt exists
    file:
      path: "{{ user_home }}/.mutt"
      state: directory

  - name: Make sure ~/.mail/gmail exists
    file:
      path: "{{ user_home }}/.mail/gmail"
      state: directory
      owner: "{{ username }}"

  - name: Link muttrc config
    script: >
          scripts/install_dotfile
          "{{ dotfiles_dir }}/ansible/roles/neomutt/files/muttrc"
          "{{ user_home }}/.mutt/muttrc"

  - name: Link mbsync service
    script: >
          scripts/install_dotfile
          "{{ dotfiles_dir }}/ansible/roles/neomutt/files/mbsync@.service"
          "/etc/systemd/system/mbsync@.service"

  - name: Link mbsync timer
    script: >
          scripts/install_dotfile
          "{{ dotfiles_dir }}/ansible/roles/neomutt/files/mbsync@.timer"
          "/etc/systemd/system/mbsync@.timer"

  - name: Enable mbsync timer
    command: systemctl enable mbsync@johan.timer

  - name: Start mbsync timer
    command: systemctl start mbsync@johan.timer
