
  - name: Link isync config
    become: true
    script: >
          scripts/install_dotfile
          "{{ dotfiles_dir }}/ansible/roles/neomutt/files/mbsyncrc"
          "{{ user_home }}/.mbsyncrc"

  - name: Make sure dirs exists
    file:
      path: "{{ user_home }}/.mutt/scripts"
      state: directory
      owner: "{{ username }}"

  - name: Make sure ~/.mail/gmail exists
    file:
      path: "{{ user_home }}/.mail/gmail"
      state: directory
      owner: "{{ username }}"

  - name: Link muttrc config
    script: >
          scripts/install_dotfile
          "{{ dotfiles_dir }}/ansible/roles/neomutt/files/muttrc"
          "{{ user_home }}/.mutt/muttrc"

  - name: Link mutt script
    script: >
          scripts/install_dotfile
          "{{ dotfiles_dir }}/ansible/roles/neomutt/files/view_attachment.sh"
          "{{ user_home }}/.mutt/scripts/view_attachment.sh"
          --executable
    become_user: "{{ username }}"

  - name: Link scripts
    script: >
          scripts/install_dotfile
          "{{ dotfiles_dir }}/ansible/roles/neomutt/files/{{ item }}"
          "{{ user_home }}/.local/bin/{{ item }}"
          --executable
    become_user: "{{ username }}"
    with_items:
      - open
      - notmuch-hook
      - mbsync-launcher

  - name: Link ~/.mailcap
    script: >
          scripts/install_dotfile
          "{{ dotfiles_dir }}/ansible/roles/neomutt/files/mailcap"
          "{{ user_home }}/.mailcap"
    become_user: "{{ username }}"

  - name: Link mailboxes
    script: >
          scripts/install_dotfile
          "{{ dotfiles_dir }}/ansible/roles/neomutt/files/mailboxes"
          "{{ user_home }}/.mutt/mailboxes"
    become_user: "{{ username }}"

  - name: Link ~/.notmuch-config
    script: >
          scripts/install_dotfile
          "{{ dotfiles_dir }}/ansible/roles/neomutt/files/notmuch-config"
          "{{ user_home }}/.notmuch-config"
    become_user: "{{ username }}"

  - name: Setup mbsync cron job
    cron:
      name: "Sync mails"
      minute: "*/3"
      job: "~/.local/bin/mbsync-launcher >> ~/.local/log/mbsync.log 2>&1"
    become_user: "{{ username }}"
    when: not ci

